FROM pandoc/core

RUN apk update && apk add --no-cache ranger vim bash coreutils nodejs yarn git

RUN addgroup -S node && adduser -S node -G node

WORKDIR /home/node/icml

RUN chown -R node:node /home/node/icml

USER node

COPY --chown=node:node package.json ./package.json
COPY --chown=node:node yarn.lock ./yarn.lock

RUN yarn

COPY --chown=node:node . .